### ISSUE TITLE
Evaluate_anomaly_detector.m- C3D features for videos (.fc file) what's this .fc files

### ISSUE THREAD

**Issue by cervantes-loves-ai** [dolongbien/HumanBehaviorBKU#9]
i was trying to run your Evaluate_anomaly_detector.m file but you mentioned there that for C3D_CNN_Path case needed to put .fc files there but how to get that .fc files

and got error like this

ivideo =

     1

Undefined variable "Annotation_file" or class "Annotation_file.VideoName".

Error in Evaluate_Anomaly_Detector_RoadAccident (line 33)
    check=strmatch(All_Videos_scores(ivideo).name(1:end-6),Annotation_file.VideoName(1:end-3));

**Comment by cervantes-loves-ai** [comment]
now got this error

ivideo =

     1

Array indices must be positive integers or logical values.

Error in Evaluate_Anomaly_Detector_another_CLG (line 85)
            Detection_score_32shots((ss-1)*16+1:(ss-1)*16+1+15)=Predic_scores.predictions(p_c);
 
Exception in thread "Explorer NavigationContext request queue" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at com.mathworks.matlab.api.explorer.FileLocation.<init>(FileLocation.java:100)
	at com.mathworks.matlab.api.explorer.FileLocation.getParent(FileLocation.java:126)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileSystem.resolveLocation(VirtualFileSystem.java:285)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileSystem.getTarget(VirtualFileSystem.java:276)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileSystem.isMountPoint(VirtualFileSystem.java:239)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileSystem.toExternalEntry(VirtualFileSystem.java:324)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileSystem.toExternalEntry(VirtualFileSystem.java:319)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileList$MountingReceiver.receive(VirtualFileList.java:106)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileList$MountingReceiver.receive(VirtualFileList.java:95)
	at com.mathworks.util.AsyncReceiverUtils$3.receive(AsyncReceiverUtils.java:77)
	at com.mathworks.mlwidgets.explorer.model.realfs.StatToEntryAdapter.receive(StatToEntryAdapter.java:37)
	at com.mathworks.cfbutils.NativeCfb.listFiles(Native Method)
	at com.mathworks.mlwidgets.explorer.model.realfs.RealFileList.readFilesAndFolders(RealFileList.java:47)
	at com.mathworks.mlwidgets.explorer.model.overlayfs.OverlayFileList.readFilesAndFolders(OverlayFileList.java:52)
	at com.mathworks.mlwidgets.explorer.model.vfs.VirtualFileList.readFilesAndFolders(VirtualFileList.java:57)
	at com.mathworks.mlwidgets.explorer.model.table.UiFileList.readAndUpdateCache(UiFileList.java:360)
	at com.mathworks.mlwidgets.explorer.model.table.UiFileList.access$500(UiFileList.java:45)
	at com.mathworks.mlwidgets.explorer.model.table.UiFileList$6.run(UiFileList.java:325)
	at com.mathworks.util.RequestQueue.execute(RequestQueue.java:129)
	at com.mathworks.util.RequestQueue.access$000(RequestQueue.java:25)
	at com.mathworks.util.RequestQueue$2.run(RequestQueue.java:79)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dolongbien** [comment]
Hi, please take a look at Script folder and C3D feature extraction notebook in this repo.

**Comment by cervantes-loves-ai** [comment]
when tried to extract feature from C3DV0.ipynb got this error

/content/C3D/C3D-v1.0/examples/c3d_feature_extraction
WARNING: Logging before InitGoogleLogging() is written to STDERR
E1001 09:04:01.901818  4332 common.cpp:31] Cannot create Cublas handle. Cublas won't be available.
E1001 09:04:01.907130  4332 common.cpp:38] Cannot create Curand generator. Curand won't be available.
F1001 09:04:01.912302  4332 common.cpp:68] Check failed: error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected
*** Check failure stack trace: ***
c3d_sport1m_feature_extraction_video.sh: line 3:  4332 Aborted                 (core dumped) GLOG_logtosterr=1 ../../build/tools/extract_image_features.bin prototxt/c3d_sport1m_feature_extractor_video.prototxt conv3d_deepnetA_sport1m_iter_1900000 0 50 1 prototxt/output_list_video_prefix.txt fc7-1 fc6-1 prob

**Comment by dolongbien** [comment]
Make sure that you are using GColab under the GPU mode. Also, carefully prepare the necessary input files for C3D feature extraction (visit Facebook C3D repo and Document link on the README description).

**Comment by cervantes-loves-ai** [comment]
i will check, thank you. is it possible to share .fc files, because last time you shared filed regarding to c3d feature extractor but in that folder .fc files was missing. i just want to test  Evaluate_anomaly_detector.m . thanks in advance.

**Comment by dolongbien** [comment]
I can share *.fc6 files but the thing is that Evaluation code also needs corresponding mp4 video of that fc6 (which I could not share at the moment). Anyways, I will send you some for you to experiment.

**Comment by cervantes-loves-ai** [comment]
thank you so much.

**Comment by dolongbien** [comment]
Here is the OneDrive link of 15 testing videos (mp4 and fc-6). Hope this help!
https://1drv.ms/u/s!Aqh8okzKJAKvbRQm2C4FJYIdvI4?e=K7KaPE

**Comment by daiyuandong** [comment]
> Here is the OneDrive link of 15 testing videos (mp4 and fc-6). Hope this help!
> https://1drv.ms/u/s!Aqh8okzKJAKvbRQm2C4FJYIdvI4?e=K7KaPE

Your link is broken, could you please put it again? Thank you very much

**Comment by daiyuandong** [comment]
> thank you so much.

The link of the author is invalid, have you got the database? Could you please put the link? Thank you very much
